name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: 'node:lts-alpine3.12'

    steps:
      - name: Checkouut
        uses: actions/checkout@v2

      - name: Install
        run: npm ci --silent --audit=false

      - name: Build and test
        run: npm run build & npm t && wait;
